//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAPITRE
    {
        public short ANC { get; set; }
        public string CSECT { get; set; }
        public string CODEC { get; set; }
        public string LIBELLEC { get; set; }
    }
}
