//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DROITS_USER
    {
        public short CODE_USER { get; set; }
        public short CODE_TRANSACT { get; set; }
        public Nullable<decimal> A_DROIT { get; set; }
    }
}
