//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FmintEntities : DbContext
    {
        public FmintEntities()
            : base("name=FmintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAT_PIECE> CAT_PIECE { get; set; }
        public DbSet<CHAPITRE> CHAPITREs { get; set; }
        public DbSet<DROITS_USER> DROITS_USER { get; set; }
        public DbSet<FONCT> FONCTs { get; set; }
        public DbSet<GRILLE> GRILLEs { get; set; }
        public DbSet<GROUPE> GROUPEs { get; set; }
        public DbSet<LOGON> LOGONs { get; set; }
        public DbSet<PARAM> PARAMs { get; set; }
        public DbSet<PROFIL_USER> PROFIL_USER { get; set; }
        public DbSet<SEJOUR> SEJOURs { get; set; }
        public DbSet<TRANSACT_USER> TRANSACT_USER { get; set; }
        public DbSet<ZONE> ZONEs { get; set; }
        public DbSet<NATURE> NATUREs { get; set; }
        public DbSet<SEJOUR_MC> SEJOUR_MC { get; set; }
        public DbSet<DECRET> DECRETs { get; set; }
    }
}
