//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FONCT
    {
        public string N_MATTIR { get; set; }
        public string C_MATTIR { get; set; }
        public string L_NOM { get; set; }
        public string L_PREN { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> SRC { get; set; }
        public string GROUPE { get; set; }
        public string INDICE { get; set; }
        public string SRV_EMPLOYEUR { get; set; }
        public string CODE_SERV { get; set; }
        public Nullable<short> LOCAL { get; set; }
        public Nullable<System.DateTime> DATE_C { get; set; }
        public string CODE_PROVINCE { get; set; }
    }
}
