//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPE
    {
        public string CODE_FONC { get; set; }
        public string LIB_FONC { get; set; }
        public string GROUPE1 { get; set; }
    }
}
