//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGON
    {
        public string NUMMATRIC { get; set; }
        public string USER_NOM { get; set; }
        public string USER_PWD { get; set; }
        public short CODE_USER { get; set; }
        public string CLEMATRIC { get; set; }
        public string FONCTION { get; set; }
    }
}
