//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM
    {
        public string CODE_PROV { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> C_INDEX { get; set; }
        public decimal TAUX { get; set; }
        public int CSTANTE { get; set; }
        public string LIB_ENTETE { get; set; }
        public string LIB_ENTETE_SUITE { get; set; }
        public string BOITE_POSTALE { get; set; }
        public string CHEF_LIEUX { get; set; }
        public string VERSION { get; set; }
    }
}
