//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEJOUR_MC
    {
        public string SEJOUR_ID { get; set; }
        public string MT_TOTAL { get; set; }
        public string C_DEST { get; set; }
        public string C_NATU { get; set; }
        public string AN { get; set; }
        public string NUMAD { get; set; }
        public string C_PCOM { get; set; }
        public string MT_UTIL { get; set; }
        public Nullable<short> ENGAGER { get; set; }
        public Nullable<short> VALIDER { get; set; }
        public string NATURE { get; set; }
    }
}
