//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEJOUR
    {
        public int SEJOUR_ID { get; set; }
        public string MATTIR { get; set; }
        public string DATE_DEB { get; set; }
        public string DATE_FIN { get; set; }
        public string ZONE { get; set; }
        public string MT_TOTAL { get; set; }
        public string GROUPE { get; set; }
        public string PAYS { get; set; }
        public string VILLE { get; set; }
        public string OBJET { get; set; }
        public string MT_AVANCE { get; set; }
        public string MT_RESTE { get; set; }
        public string COMPTE_CREDITER { get; set; }
        public string MT_AVANCE_SEJOUR { get; set; }
        public Nullable<short> JUSTIFIER { get; set; }
        public Nullable<short> ENGAGER { get; set; }
        public Nullable<short> NB_ENGAGEMENT { get; set; }
        public string L_MT_AVANCE_SEJOUR { get; set; }
        public string L_MT_RESTE { get; set; }
    }
}
